apiVersion: v1
kind: Pod
metadata:
  #
  # This is the name that will appear in kubectl get po
  #
  name: blog-env
  labels:
    app: blog
spec:
  #
  # The specification is a list of attributes, one of which
  # is the list of containers
  # 
  containers:
  - name: blog
    image: ash002019/dockertutorial:v0.1
    ports:
      - containerPort: 8888
    env:
      - name: FLASK_PORT
        value: "8888"



    
